import { StyleSheet } from 'react-native';
import Shadows from '../constants/Shadows';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },

  /* Header */
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 8,
    right: 9,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#FF6B1A',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },

  /* Search Section with Filter Button */
  searchWrapper: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#0F172A',
    paddingVertical: 0,
  },
  clearSearchBtn: {
    padding: 4,
  },
  searchFilterBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    position: 'relative',
  },
  searchFilterBtnActive: {
    backgroundColor: '#FF6B1A',
    borderColor: '#FF6B1A',
  },
  searchFilterBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FF6B1A',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchFilterBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },

  /* Subcategories Carousel */
  subcategoriesSection: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  subcategoriesList: {
    paddingHorizontal: 16,
    gap: 12,
  },
  subcategoryItem: {
    alignItems: 'center',
    width: 76,
  },
  subcategoryAvatar: {
    width: 58,
    height: 58,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    position: 'relative',
    overflow: 'hidden',
    marginBottom: 6,
  },
  subcategoryAvatarSelected: {
    borderColor: '#FF6B1A',
    borderWidth: 2,
    backgroundColor: '#FFF7ED',
    ...Shadows.small,
  },
  subcategoryImage: {
    width: '100%',
    height: '100%',
  },
  subcategoryIconFallback: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  subcatActiveBadge: {
    position: 'absolute',
    bottom: -1,
    right: -1,
    backgroundColor: '#FF6B1A',
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  subcategoryName: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
    lineHeight: 14,
    height: 28,
  },
  subcategoryNameSelected: {
    color: '#FF6B1A',
    fontWeight: '700',
  },

  /* Compact Filter / Sort Bar: [ Filter ] [ Sort By ] [ Location ] [ Price ] */
  filterBarContainer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  filterBarScroll: {
    paddingHorizontal: 16,
    gap: 8,
    alignItems: 'center',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterChipActive: {
    backgroundColor: '#FFF7ED',
    borderColor: '#FF6B1A',
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    marginLeft: 4,
  },
  filterChipTextActive: {
    color: '#FF6B1A',
    fontWeight: '700',
  },
  filterCountBadge: {
    backgroundColor: '#FF6B1A',
    width: 17,
    height: 17,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
  filterCountText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },

  /* Active Filter Tags */
  activeFilterSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 2,
    flexWrap: 'wrap',
    gap: 6,
  },
  filterTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FFEDD5',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 12,
  },
  filterTagText: {
    fontSize: 11,
    color: '#FF6B1A',
    fontWeight: '600',
    marginRight: 4,
  },
  clearAllTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  clearAllTagText: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },

  /* Featured Section */
  featuredSection: {
    marginTop: 12,
    marginBottom: 6,
  },
  featuredHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  featuredTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  featuredTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  featuredSparkleBadge: {
    backgroundColor: '#FFF7ED',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 6,
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  featuredSparkleText: {
    fontSize: 9,
    color: '#FF6B1A',
    fontWeight: '700',
  },
  featuredList: {
    paddingHorizontal: 16,
    gap: 12,
  },
  featuredCard: {
    width: 210,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    overflow: 'hidden',
    ...Shadows.small,
  },
  featuredImageContainer: {
    position: 'relative',
    height: 120,
    backgroundColor: '#F8FAFC',
  },
  featuredImage: {
    width: '100%',
    height: '100%',
  },
  featuredBadgePill: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#FF6B1A',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  featuredBadgeText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  featuredFavBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    width: 26,
    height: 26,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
  },
  featuredInfo: {
    padding: 10,
  },
  featuredPrice: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 2,
  },
  featuredProductTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    lineHeight: 16,
    marginBottom: 6,
    height: 32,
  },
  featuredLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  featuredLocationText: {
    fontSize: 10,
    color: '#64748B',
    marginLeft: 3,
    fontWeight: '500',
  },

  /* Product Listing Section */
  listingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 14,
    marginBottom: 10,
  },
  listingTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  listingCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },

  /* Products Grid */
  gridContainer: {
    paddingBottom: 24,
  },
  row: {
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 12,
  },

  /* Empty State */
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  emptyIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#FFF7ED',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: '#FFEDD5',
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 6,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 18,
  },
  clearFiltersBtn: {
    backgroundColor: '#FF6B1A',
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#FF6B1A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  clearFiltersBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    marginLeft: 6,
  },
});
